import React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import {Container} from 'semantic-ui-react';
import Header from 'components/Header';

import styles from '../styles/Layout.module.css'

function Layout(props) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />

			<Container>
				<main className={styles.main2}>
					{props.children}
				</main>

				<footer className={styles.footer}>
					<a
						href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
						target="_blank"
						rel="noopener noreferrer"
					>
						Powered by{' '}
						<span className={styles.logo}>
							<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
						</span>
					</a>
				</footer>
			</Container>
		</>
	)
}

export async function getStaticProps(context) {
	const campaigns = await factory.methods.getdeployedCampaigns().call();
	return {
		props: {
			campaigns: campaigns,
		}
	}
}

export default Layout;